export interface PlayerPagedDto {
  readonly playerId: number;
  readonly playerName: string;
  readonly teamName: string;
  readonly position: string;
  readonly cost: number;
  readonly bonus: number;
  readonly totalPoints: number;
  readonly minutes: number;
  readonly goals: number;
  readonly assists: number;
  readonly cleanSheets: number;
  readonly pointsPerGame: number;
  readonly form: number;
  readonly expectedAssistsPer90: number;
  readonly expectedGoalInvolvementsPer90: number;
  readonly expectedGoalsPer90: number;
  readonly expectedGoalsConcededPer90: number;
  readonly defensiveContributionPer90: number;
  readonly savesPer90: number;
  readonly selectedByPercent: number;
  readonly valueSeason: number;
  readonly valueForm: number;
  readonly bps: number;
  readonly influence: number;
  readonly creativity: number;
  readonly threat: number;
  readonly ictIndex: number;
}
